### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by dtran320** [dtran320/django-dropzone#1]
Hey @chrisvxd, just wondering-- are you're still maintaining this project? I'm asking because we've created a fork or dropzone over at https://github.com/Crowdbooster/django-dropzone/, but ended up rewriting a significant portion of it to work for our purposes. 

We'd like to make sure the open source community can benefit from our efforts as much as we've benefited from being able to start work off your project, but want to make sure we acknowledge your work appropriately. We can rename the project to something else and give acknowledgement back to this project, or keep the name if you'd prefer the django-dropzone name to live on. In any case, please let me know!

**Comment by chrisvxd** [comment]
Hi @dtran320! Took me by surprise.

No, this project is no longer being maintained. I never really expected anyone to use it!

Do what you wish with it! Rename if you want, but don't feel obliged to. I'm totally easy with whatever you choose to do.

If you're really interested, I can transfer ownership of the original repository to you so that you aren't running off a fork.

**Comment by dtran320** [comment]
Hey @chrisvxd, that'd be great! Thanks so much for offering to do that. We'll update the `README.md` to give you full credit for starting the project. Could you please transfer it to `Crowdbooster/django-dropzone`?

**Comment by chrisvxd** [comment]
Done! No problemo. Also, Crowdbooster looks cool. Maybe I'll check it out.
